// <auto-generated />
using System;
using Cms.Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cms.Api.Data.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    [Migration("20260710072051_AddUniqueAdminUsername")]
    partial class AddUniqueAdminUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cms.Api.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Cms.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Experience"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Learning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lifestyle"
                        });
                });

            modelBuilder.Entity("Cms.Api.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CoverImageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UpdatedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CoverImageId");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("UpdatedByAdminId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Cms.Api.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            FilePath = "/images/defaults/experience-1.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            FilePath = "/images/defaults/experience-2.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            FilePath = "/images/defaults/experience-3.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            FilePath = "/images/defaults/learning-1.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            FilePath = "/images/defaults/learning-2.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            FilePath = "/images/defaults/learning-3.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            FilePath = "/images/defaults/lifestyle-1.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            FilePath = "/images/defaults/lifestyle-2.png",
                            Type = "Default"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            FilePath = "/images/defaults/lifestyle-3.png",
                            Type = "Default"
                        });
                });

            modelBuilder.Entity("Cms.Api.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectionImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("SectionImageId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Cms.Api.Entities.Content", b =>
                {
                    b.HasOne("Cms.Api.Entities.Category", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cms.Api.Entities.Image", "CoverImage")
                        .WithMany("Contents")
                        .HasForeignKey("CoverImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cms.Api.Entities.Admin", "CreatedByAdmin")
                        .WithMany("CreatedContents")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cms.Api.Entities.Admin", "UpdatedByAdmin")
                        .WithMany("UpdatedContents")
                        .HasForeignKey("UpdatedByAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CoverImage");

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("Cms.Api.Entities.Image", b =>
                {
                    b.HasOne("Cms.Api.Entities.Category", "Category")
                        .WithMany("Images")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Cms.Api.Entities.Section", b =>
                {
                    b.HasOne("Cms.Api.Entities.Content", "Content")
                        .WithMany("Sections")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cms.Api.Entities.Image", "SectionImage")
                        .WithMany("Sections")
                        .HasForeignKey("SectionImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("SectionImage");
                });

            modelBuilder.Entity("Cms.Api.Entities.Admin", b =>
                {
                    b.Navigation("CreatedContents");

                    b.Navigation("UpdatedContents");
                });

            modelBuilder.Entity("Cms.Api.Entities.Category", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Cms.Api.Entities.Content", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Cms.Api.Entities.Image", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
